export const AMOUNT_PER_LOYALTY_POINT = 1000;
export const LOW_STOCK_THRESHOLD = 5;
export const FLASH_SALE_PROBABILITY = 0.3;
export const FLASH_SALE_DISCOUNT = 0.8;
export const SUGGESTED_PRODUCT_DISCOUNT = 0.95;