const DISCOUNT_PRODUCT_COUNT = 10;

const DISCOUNT_5_PERCENT = 0.05;
const DISCOUNT_10_PERCENT = 0.1;
const DISCOUNT_15_PERCENT = 0.15;
const DISCOUNT_20_PERCENT = 0.2;
const DISCOUNT_25_PERCENT = 0.25;

const discountRates = {
  p1: DISCOUNT_10_PERCENT,
  p2: DISCOUNT_15_PERCENT,
  p3: DISCOUNT_20_PERCENT,
  p4: DISCOUNT_5_PERCENT,
  p5: DISCOUNT_25_PERCENT,
};

const DISCOUNT_25_PERCENT_PRODUCT_COUNT = 30;
const ALERT_SHORT_STOCK = '재고가 부족합니다.';

export {
  DISCOUNT_PRODUCT_COUNT,
  DISCOUNT_5_PERCENT,
  DISCOUNT_10_PERCENT,
  DISCOUNT_15_PERCENT,
  DISCOUNT_20_PERCENT,
  DISCOUNT_25_PERCENT,
  discountRates,
  DISCOUNT_25_PERCENT_PRODUCT_COUNT,
  ALERT_SHORT_STOCK,
};
